# coimpres_cuba/context_processors.py
def i18n_context(request):
    """
    Context processor para manejar las traducciones globalmente en todas las plantillas.
    Esto permite que el navbar, footer y otros elementos del layout base se traduzcan.
    """
    # Si se pasa lang por parámetro, lo guardamos en sesión y lo usamos
    if 'lang' in request.GET:
        lang = request.GET.get('lang', 'es')
        if lang in ['es', 'en', 'it']:  # Solo idiomas válidos
            request.session['selected_language'] = lang
    else:
        # Si no hay parámetro, usamos el idioma guardado en sesión o español por defecto
        lang = request.session.get('selected_language', 'es')
    
    # Definiciones de texto en diferentes idiomas - COIMPRE S.r.l.
    i18n_translations = {
        'en': {
            # Navegación
            'home': 'Home',
            'products': 'Products',
            'suppliers': 'Suppliers',
            'about': 'About Us',
            'contact': 'Contact',
            'exclusive_orders': 'Exclusive Orders',
            
            # Información oficial COIMPRE S.r.l.
            'company_tagline': 'COIMPRE S.r.l. - Made in Italy Products since 2014',
            'since_2014': 'Since 2014',
            'office_miramar': 'Miramar Office',
            'customs_warehouse': 'Customs Warehouse',
            'office_cuba': 'Cuba Office',
            'miramar_havana': 'Miramar, Havana',
            
            # Footer
            'footer_description': 'Italian company specialized in import and export of Made in Italy products for construction and food. Present in Cuba since 2023.',
            'quick_links': 'Quick Links',
            'rights': 'All Rights Reserved',
            'made_with_love': 'Made with',
            'in_italy': 'in Italy',
            
            # Botones y acciones comunes
            'view_products': 'View Products',
            'contact_us': 'Contact Us',
            'view_details': 'View Details',
            'all_products': 'View All Products',
            
            # Contenido general
            'hero_title': 'Quality Italian Products in Cuba',
            'hero_subtitle': 'We bring the best Italian quality directly to Havana. Wide catalog of products from the best Italian brands.',
            'about_us': 'About Us',
            'our_story': 'Our Story',
            'story_content': 'Founded in 2014, COIMPRE S.r.l. brings authentic Italian products to Cuban customers. With a passion for quality and tradition, we source the finest products directly from Italian manufacturers.',
            'our_mission': 'Our Mission',
            'mission_content': 'Provide complete solutions and high-quality Made in Italy products for the construction and food sectors, tailored to the needs of the Cuban market, with a focus on excellence, innovation, and specialized technical support.',
            'our_values': 'Our Values',
            'value_quality': 'Premium Quality',
            'value_quality_desc': 'We select only the finest Italian products',
            'value_authenticity': 'Authenticity',
            'value_authenticity_desc': 'We guarantee the authenticity of all our products',
            'value_tradition': 'Italian Tradition',
            'value_tradition_desc': 'We respect Italian tradition and craftsmanship',
            'value_customer': 'Customer Satisfaction',
            'value_customer_desc': 'Your satisfaction is our priority',
            'featured_products': 'Featured Products',
            'featured_subtitle': 'Explore our selection of premium Italian products',
            
            # Productos
            'product_catalog': 'Product Catalog',
            'search_products': 'Search products...',
            'search': 'Search',
            'applied_filters': 'Applied filters:',
            'search_term': 'Search',
            'category': 'Category',
            'subcategory': 'Subcategory',
            'supplier': 'Supplier',
            'status': 'Status',
            'showing_results': 'Showing',
            'of_total': 'of',
            'products_found': 'products',
            'no_products': 'No products found',
            'no_products_available': 'No products are available at this time.',
            'filters': 'Filters',
            'show_filters': 'Show',
            'all_categories': 'All',
            'all_subcategories': 'All',
            'all_suppliers': 'All',
            'all_status': 'All',
            'apply': 'Apply',
            'clear': 'Clear',
            'first_page': 'First',
            'previous_page': 'Previous',
            'next_page': 'Next',
            'last_page': 'Last',
            'current_page': '(current page)',
            'page_info': 'Page',
            'total_products': 'products in total',
            'page_navigation': 'Page navigation',
            
            # Proveedores
            'our_suppliers': 'Our Suppliers',
            'suppliers_subtitle': 'High quality products directly from Italy. Meet our business partners and explore their specialized catalogs.',
            'products_count': 'product',
            'products_count_plural': 'products',
            'download_catalog': 'Download Catalog',
            'catalog_not_available': 'Catalog not available',
            'no_suppliers': 'No suppliers available',
            'no_suppliers_message': 'We currently have no suppliers with active products in our catalog.\nCheck back soon to see our new additions.',
            'guaranteed_quality': 'Guaranteed Quality',
            'quality_message': 'All our suppliers are carefully selected to ensure the highest quality in Italian products. Each catalog contains detailed information on technical specifications, certifications and quality guarantees.',
            
            # Pedidos Exclusivos
            'exclusive_orders_title': 'Exclusive Orders',
            'exclusive_orders_subtitle': 'Looking for specific products that you can\'t find in our catalogs?',
            'exclusive_orders_description': 'With more than 1000 products available, we can get what you need from Italy!',
            'direct_import': 'Direct import',
            'authentic_products': 'Authentic products',
            'competitive_prices': 'Competitive prices',
            'contact_whatsapp': 'Contact us on WhatsApp!',
            'whatsapp_description': 'The fastest and most direct way to place your exclusive order. Our team will help you find exactly what you need.',
            'start_whatsapp': 'Start WhatsApp Chat',
            'how_to_order': 'How to place your order?',
            'order_step_1': 'Send us the product information',
            'order_step_1_desc': 'Name, brand, model, or any details you have about the product you are looking for.',
            'order_step_2': 'Receive personalized quote',
            'order_step_2_desc': 'In 24-48 hours we will send you price, availability and delivery time.',
            'order_step_3': 'Confirm your order',
            'order_step_3_desc': 'Once the quote is approved, we process your order directly with Italy.',
            'order_step_4': 'Receive your product',
            'order_step_4_desc': 'We will notify you when your order arrives in Havana to coordinate delivery.',
            'important_info': 'Important Information',
            'response_time': 'Response Time',
            'response_time_desc': 'We respond to inquiries Monday through Friday from 9:00 AM to 6:00 PM. We check urgent messages on weekends.',
            'delivery_time': 'Delivery Time',
            'delivery_time_desc': 'Exclusive orders take 15-30 days from Italy to Havana, depending on product availability.',
            'authenticity_guarantee': 'Authenticity Guarantee',
            'authenticity_desc': 'All our products are 100% authentic, imported directly from authorized distributors in Italy.',
            'payment_methods': 'Payment Methods',
            'payment_desc': 'We accept multiple forms of payment. We will inform you of the available options when confirming your order.',
            'other_contact': 'Other contact methods:',
            'most_requested': 'Most requested products',
            'popular_products_desc': 'These are some of the products that our customers usually order',
            'electronics': 'Electronics',
            'electronics_desc': 'Gadgets, components',
            'art_design': 'Art & Design',
            'art_design_desc': 'Decoration, crafts',
            'tools': 'Tools',
            'tools_desc': 'Professional, home',
            'health_beauty': 'Health & Beauty',
            'health_beauty_desc': 'Cosmetics, care',
            'not_found_question': 'Can\'t find what you\'re looking for?',
            'consult_specific': 'Consult Specific Product',
            
            # Selector de idiomas
            'language': 'Language',
            'spanish': 'Spanish',
            'english': 'English',
            'italian': 'Italian'
        },
        'es': {
            # Navegación
            'home': 'Inicio',
            'products': 'Productos',
            'suppliers': 'Proveedores',
            'about': 'Sobre Nosotros',
            'contact': 'Contacto',
            'exclusive_orders': 'Pedidos Exclusivos',
            
            # Información oficial COIMPRE S.r.l.
            'company_tagline': 'COIMPRE S.r.l. - Productos Made in Italy desde 2014',
            'since_2014': 'Desde 2014',
            'office_miramar': 'Oficina en Miramar',
            'customs_warehouse': 'Depósito Aduanero',
            'office_cuba': 'Oficina Cuba',
            'miramar_havana': 'Miramar, La Habana',
            
            # Footer
            'footer_description': 'Empresa italiana especializada en importación y exportación de productos Made in Italy para construcción y alimentación. Presente en Cuba desde 2023.',
            'quick_links': 'Enlaces Rápidos',
            'rights': 'Todos los Derechos Reservados',
            'made_with_love': 'Hecho con',
            'in_italy': 'en Italia',
            
            # Botones y acciones comunes
            'view_products': 'Ver Productos',
            'contact_us': 'Contáctanos',
            'view_details': 'Ver Detalles',
            'all_products': 'Ver Todos los Productos',
            
            # Contenido general
            'hero_title': 'Productos Italianos de Calidad en Cuba',
            'hero_subtitle': 'Traemos la mejor calidad italiana directamente a La Habana. Amplio catálogo de productos de las mejores marcas italianas.',
            'about_us': 'Sobre Nosotros',
            'our_story': 'Nuestra Historia',
            'story_content': 'Fundada en 2014, COIMPRE S.r.l. trae productos auténticos italianos a los clientes cubanos. Con pasión por la calidad y la tradición, obtenemos los mejores productos directamente de fabricantes italianos.',
            'our_mission': 'Nuestra Misión',
            'mission_content': 'Proporcionar soluciones completas y productos Made in Italy de alta calidad para los sectores de la construcción y la alimentación, adaptados a las necesidades del mercado cubano, con un enfoque en la excelencia, la innovación y el soporte técnico especializado.',
            'our_values': 'Nuestros Valores',
            'value_quality': 'Calidad Premium',
            'value_quality_desc': 'Seleccionamos solo los mejores productos italianos',
            'value_authenticity': 'Autenticidad',
            'value_authenticity_desc': 'Garantizamos la autenticidad de todos nuestros productos',
            'value_tradition': 'Tradición Italiana',
            'value_tradition_desc': 'Respetamos la tradición y artesanía italiana',
            'value_customer': 'Satisfacción del Cliente',
            'value_customer_desc': 'Tu satisfacción es nuestra prioridad',
            'featured_products': 'Productos Destacados',
            'featured_subtitle': 'Explora nuestra selección de productos italianos premium',
            
            # Productos
            'product_catalog': 'Catálogo de Productos',
            'search_products': 'Buscar productos...',
            'search': 'Buscar',
            'applied_filters': 'Filtros aplicados:',
            'search_term': 'Búsqueda',
            'category': 'Categoría',
            'subcategory': 'Subcategoría',
            'supplier': 'Proveedor',
            'status': 'Estatus',
            'showing_results': 'Mostrando',
            'of_total': 'de',
            'products_found': 'productos',
            'no_products': 'No se encontraron productos',
            'no_products_available': 'No hay productos disponibles en este momento.',
            'filters': 'Filtros',
            'show_filters': 'Mostrar',
            'all_categories': 'Todas',
            'all_subcategories': 'Todas',
            'all_suppliers': 'Todos',
            'all_status': 'Todos',
            'apply': 'Aplicar',
            'clear': 'Limpiar',
            'first_page': 'Primera',
            'previous_page': 'Anterior',
            'next_page': 'Siguiente',
            'last_page': 'Última',
            'current_page': '(página actual)',
            'page_info': 'Página',
            'total_products': 'productos en total',
            'page_navigation': 'Navegación de páginas',
            
            # Proveedores
            'our_suppliers': 'Nuestros Proveedores',
            'suppliers_subtitle': 'Productos de alta calidad directamente desde Italia. Conoce a nuestros socios comerciales y explora sus catálogos especializados.',
            'products_count': 'producto',
            'products_count_plural': 'productos',
            'download_catalog': 'Descargar Catálogo',
            'catalog_not_available': 'Catálogo no disponible',
            'no_suppliers': 'No hay proveedores disponibles',
            'no_suppliers_message': 'Actualmente no tenemos proveedores con productos activos en nuestro catálogo.\nVuelve pronto para ver nuestras nuevas incorporaciones.',
            'guaranteed_quality': 'Calidad Garantizada',
            'quality_message': 'Todos nuestros proveedores son cuidadosamente seleccionados para asegurar la más alta calidad en productos italianos. Cada catálogo contiene información detallada sobre especificaciones técnicas, certificaciones y garantías de calidad.',
            
            # Pedidos Exclusivos
            'exclusive_orders_title': 'Pedidos Exclusivos',
            'exclusive_orders_subtitle': '¿Buscas productos específicos que no encuentras en nuestros catálogos?',
            'exclusive_orders_description': '¡Con más de 1000 productos disponibles, podemos conseguir lo que necesites desde Italia!',
            'direct_import': 'Importación directa',
            'authentic_products': 'Productos auténticos',
            'competitive_prices': 'Precios competitivos',
            'contact_whatsapp': '¡Contáctanos por WhatsApp!',
            'whatsapp_description': 'La forma más rápida y directa de hacer tu pedido exclusivo. Nuestro equipo te ayudará a encontrar exactamente lo que necesitas.',
            'start_whatsapp': 'Iniciar Chat en WhatsApp',
            'how_to_order': '¿Cómo hacer tu pedido?',
            'order_step_1': 'Envíanos la información del producto',
            'order_step_1_desc': 'Nombre, marca, modelo, o cualquier detalle que tengas del producto que buscas.',
            'order_step_2': 'Recibe cotización personalizada',
            'order_step_2_desc': 'En 24-48 horas te enviaremos precio, disponibilidad y tiempo de entrega.',
            'order_step_3': 'Confirma tu pedido',
            'order_step_3_desc': 'Una vez aprobada la cotización, procesamos tu pedido directamente con Italia.',
            'order_step_4': 'Recibe tu producto',
            'order_step_4_desc': 'Te notificaremos cuando tu pedido llegue a La Habana para coordinar la entrega.',
            'important_info': 'Información Importante',
            'response_time': 'Tiempo de Respuesta',
            'response_time_desc': 'Respondemos consultas de lunes a viernes de 9:00 AM a 6:00 PM. Los fines de semana revisamos mensajes urgentes.',
            'delivery_time': 'Tiempo de Entrega',
            'delivery_time_desc': 'Los pedidos exclusivos toman entre 15-30 días desde Italia hasta La Habana, dependiendo de la disponibilidad del producto.',
            'authenticity_guarantee': 'Garantía de Autenticidad',
            'authenticity_desc': 'Todos nuestros productos son 100% auténticos, importados directamente desde distribuidores autorizados en Italia.',
            'payment_methods': 'Métodos de Pago',
            'payment_desc': 'Aceptamos múltiples formas de pago. Te informaremos las opciones disponibles al momento de confirmar tu pedido.',
            'other_contact': 'Otros métodos de contacto:',
            'most_requested': 'Productos más solicitados',
            'popular_products_desc': 'Estos son algunos de los productos que nuestros clientes suelen pedir',
            'electronics': 'Electrónicos',
            'electronics_desc': 'Gadgets, componentes',
            'art_design': 'Arte & Diseño',
            'art_design_desc': 'Decoración, artesanías',
            'tools': 'Herramientas',
            'tools_desc': 'Profesionales, hogar',
            'health_beauty': 'Salud & Belleza',
            'health_beauty_desc': 'Cosméticos, cuidado',
            'not_found_question': '¿No encuentras lo que buscas?',
            'consult_specific': 'Consultar Producto Específico',
            
            # Selector de idiomas
            'language': 'Idioma',
            'spanish': 'Español',
            'english': 'Inglés',
            'italian': 'Italiano'
        },
        'it': {
            # Navegación
            'home': 'Home',
            'products': 'Prodotti',
            'suppliers': 'Fornitori',
            'about': 'Chi Siamo',
            'contact': 'Contatti',
            'exclusive_orders': 'Ordini Esclusivi',
            
            # Información oficial COIMPRE S.r.l.
            'company_tagline': 'COIMPRE S.r.l. - Prodotti Made in Italy dal 2014',
            'since_2014': 'Dal 2014',
            'office_miramar': 'Ufficio Miramar',
            'customs_warehouse': 'Deposito Doganale',
            'office_cuba': 'Ufficio Cuba',
            'miramar_havana': 'Miramar, L\'Avana',
            
            # Footer
            'footer_description': 'Azienda italiana specializzata nell\'importazione ed esportazione di prodotti Made in Italy per edilizia e alimentazione. Presente a Cuba dal 2023.',
            'quick_links': 'Collegamenti Rapidi',
            'rights': 'Tutti i Diritti Riservati',
            'made_with_love': 'Fatto con',
            'in_italy': 'in Italia',
            
            # Botones y acciones comunes
            'view_products': 'Visualizza Prodotti',
            'contact_us': 'Contattaci',
            'view_details': 'Visualizza Dettagli',
            'all_products': 'Visualizza Tutti i Prodotti',
            
            # Contenido general
            'hero_title': 'Prodotti Italiani di Qualità a Cuba',
            'hero_subtitle': 'Portiamo la migliore qualità italiana direttamente all\'Avana. Ampio catalogo di prodotti dei migliori marchi italiani.',
            'about_us': 'Chi Siamo',
            'our_story': 'La Nostra Storia',
            'story_content': 'Fondata nel 2014, COIMPRE S.r.l. porta autentici prodotti italiani ai clienti cubani. Con passione per la qualità e la tradizione, acquistiamo i migliori prodotti direttamente dai produttori italiani.',
            'our_mission': 'La Nostra Missione',
            'mission_content': 'Fornire soluzioni complete e prodotti Made in Italy di alta qualità per i settori dell\'edilizia e dell\'alimentazione, adattati alle esigenze del mercato cubano, con un\'attenzione all\'eccellenza, all\'innovazione e al supporto tecnico specializzato.',
            'our_values': 'I Nostri Valori',
            'value_quality': 'Qualità Premium',
            'value_quality_desc': 'Selezioniamo solo i migliori prodotti italiani',
            'value_authenticity': 'Autenticità',
            'value_authenticity_desc': 'Garantiamo l\'autenticità di tutti i nostri prodotti',
            'value_tradition': 'Tradizione Italiana',
            'value_tradition_desc': 'Rispettiamo la tradizione e l\'artigianalità italiana',
            'value_customer': 'Soddisfazione del Cliente',
            'value_customer_desc': 'La tua soddisfazione è la nostra priorità',
            'featured_products': 'Prodotti in Evidenza',
            'featured_subtitle': 'Esplora la nostra selezione di prodotti italiani premium',
            
            # Productos
            'product_catalog': 'Catalogo Prodotti',
            'search_products': 'Cerca prodotti...',
            'search': 'Cerca',
            'applied_filters': 'Filtri applicati:',
            'search_term': 'Ricerca',
            'category': 'Categoria',
            'subcategory': 'Sottocategoria',
            'supplier': 'Fornitore',
            'status': 'Stato',
            'showing_results': 'Mostrando',
            'of_total': 'di',
            'products_found': 'prodotti',
            'no_products': 'Nessun prodotto trovato',
            'no_products_available': 'Nessun prodotto disponibile al momento.',
            'filters': 'Filtri',
            'show_filters': 'Mostra',
            'all_categories': 'Tutte',
            'all_subcategories': 'Tutte',
            'all_suppliers': 'Tutti',
            'all_status': 'Tutti',
            'apply': 'Applica',
            'clear': 'Pulisci',
            'first_page': 'Prima',
            'previous_page': 'Precedente',
            'next_page': 'Successiva',
            'last_page': 'Ultima',
            'current_page': '(pagina corrente)',
            'page_info': 'Pagina',
            'total_products': 'prodotti in totale',
            'page_navigation': 'Navigazione pagine',
            
            # Proveedores
            'our_suppliers': 'I Nostri Fornitori',
            'suppliers_subtitle': 'Prodotti di alta qualità direttamente dall\'Italia. Conosci i nostri partner commerciali ed esplora i loro cataloghi specializzati.',
            'products_count': 'prodotto',
            'products_count_plural': 'prodotti',
            'download_catalog': 'Scarica Catalogo',
            'catalog_not_available': 'Catalogo non disponibile',
            'no_suppliers': 'Nessun fornitore disponibile',
            'no_suppliers_message': 'Attualmente non abbiamo fornitori con prodotti attivi nel nostro catalogo.\nTorna presto per vedere le nostre nuove aggiunte.',
            'guaranteed_quality': 'Qualità Garantita',
            'quality_message': 'Tutti i nostri fornitori sono accuratamente selezionati per garantire la massima qualità nei prodotti italiani. Ogni catalogo contiene informazioni dettagliate su specifiche tecniche, certificazioni e garanzie di qualità.',
            
            # Pedidos Exclusivos
            'exclusive_orders_title': 'Ordini Esclusivi',
            'exclusive_orders_subtitle': 'Cerchi prodotti specifici che non trovi nei nostri cataloghi?',
            'exclusive_orders_description': 'Con più di 1000 prodotti disponibili, possiamo ottenere quello che ti serve dall\'Italia!',
            'direct_import': 'Importazione diretta',
            'authentic_products': 'Prodotti autentici',
            'competitive_prices': 'Prezzi competitivi',
            'contact_whatsapp': 'Contattaci su WhatsApp!',
            'whatsapp_description': 'Il modo più veloce e diretto per effettuare il tuo ordine esclusivo. Il nostro team ti aiuterà a trovare esattamente quello che ti serve.',
            'start_whatsapp': 'Inizia Chat WhatsApp',
            'how_to_order': 'Come effettuare il tuo ordine?',
            'order_step_1': 'Inviaci le informazioni del prodotto',
            'order_step_1_desc': 'Nome, marca, modello, o qualsiasi dettaglio che hai del prodotto che cerchi.',
            'order_step_2': 'Ricevi preventivo personalizzato',
            'order_step_2_desc': 'In 24-48 ore ti invieremo prezzo, disponibilità e tempi di consegna.',
            'order_step_3': 'Conferma il tuo ordine',
            'order_step_3_desc': 'Una volta approvato il preventivo, processiamo il tuo ordine direttamente con l\'Italia.',
            'order_step_4': 'Ricevi il tuo prodotto',
            'order_step_4_desc': 'Ti avviseremo quando il tuo ordine arriva all\'Avana per coordinare la consegna.',
            'important_info': 'Informazioni Importanti',
            'response_time': 'Tempo di Risposta',
            'response_time_desc': 'Rispondiamo alle richieste dal lunedì al venerdì dalle 9:00 alle 18:00. Nel weekend controlliamo i messaggi urgenti.',
            'delivery_time': 'Tempo di Consegna',
            'delivery_time_desc': 'Gli ordini esclusivi richiedono 15-30 giorni dall\'Italia all\'Avana, a seconda della disponibilità del prodotto.',
            'authenticity_guarantee': 'Garanzia di Autenticità',
            'authenticity_desc': 'Tutti i nostri prodotti sono 100% autentici, importati direttamente da distributori autorizzati in Italia.',
            'payment_methods': 'Metodi di Pagamento',
            'payment_desc': 'Accettiamo diverse forme di pagamento. Ti informeremo delle opzioni disponibili al momento della conferma dell\'ordine.',
            'other_contact': 'Altri metodi di contatto:',
            'most_requested': 'Prodotti più richiesti',
            'popular_products_desc': 'Questi sono alcuni dei prodotti che i nostri clienti solitamente ordinano',
            'electronics': 'Elettronica',
            'electronics_desc': 'Gadget, componenti',
            'art_design': 'Arte & Design',
            'art_design_desc': 'Decorazione, artigianato',
            'tools': 'Attrezzi',
            'tools_desc': 'Professionali, casa',
            'health_beauty': 'Salute & Bellezza',
            'health_beauty_desc': 'Cosmetici, cura',
            'not_found_question': 'Non trovi quello che cerchi?',
            'consult_specific': 'Consulta Prodotto Specifico',
            
            # Selector de idiomas
            'language': 'Lingua',
            'spanish': 'Spagnolo',
            'english': 'Inglese',
            'italian': 'Italiano'
        }
    }
    
    # Usar el idioma seleccionado o español por defecto
    i18n_selected = i18n_translations.get(lang, i18n_translations['es'])
    
    return {
        'lang': lang,
        'i18n': i18n_selected,
    }