# Generated by Django 5.2.4 on 2025-10-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen de Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='productos.product', verbose_name='Productos Relacionados'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('construccion', 'Construcción'), ('comida', 'Comida'), ('herramientas', 'Herramientas'), ('tecnologia', 'Tecnología'), ('hogar', 'Hogar y Decoración'), ('industrial', 'Equipamiento Industrial')], max_length=120, verbose_name='Nombre'),
        ),
    ]
