# Generated by Django 5.2.4 on 2025-10-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_category_image_product_related_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='related_products',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('construccion', 'Construcción'), ('comida', 'Comida')], max_length=120, verbose_name='Nombre'),
        ),
    ]
