# Generated by Django 5.2.4 on 2025-10-07 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estatus de Procedencia',
                'verbose_name_plural': 'Estatus de Procedencia',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_procedencia',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video del Producto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='catalogo',
            field=models.FileField(blank=True, null=True, upload_to='catalogos/', verbose_name='Catálogo (PDF)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_unico',
            field=models.CharField(default='temp_id', help_text='Identificador único del proveedor', max_length=50, unique=True, verbose_name='ID Único'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='product',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.estatus', verbose_name='Estatus de Procedencia'),
        ),
        migrations.DeleteModel(
            name='StatusProcedencia',
        ),
    ]
