# Generated by Django 5.2.4 on 2025-10-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_estatus_remove_product_status_procedencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-destacado', '-en_oferta', '-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Producto Destacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='en_oferta',
            field=models.BooleanField(default=False, verbose_name='En Oferta'),
        ),
    ]
