# Generated by Django 5.2.4 on 2025-10-09 00:26

from django.db import migrations


def clear_main_videos(apps, schema_editor):
    """Desactivar todos los is_main de videos ya que no se usará más"""
    ProductVideo = apps.get_model('productos', 'ProductVideo')
    ProductVideo.objects.filter(is_main=True).update(is_main=False)


def reverse_clear_main_videos(apps, schema_editor):
    """Reversa de la operación - no hacer nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_productimage_productvideo'),
    ]

    operations = [
        migrations.RunPython(clear_main_videos, reverse_clear_main_videos),
    ]
