# Generated by Django 5.2.4 on 2025-10-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20251008_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['order'], 'verbose_name': 'Video de Galería', 'verbose_name_plural': 'Videos de Galería'},
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='is_main',
        ),
    ]
