# Generated by Django 5.2.4 on 2025-11-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_productvideo_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='productos_p_slug_50559c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'destacado'], name='productos_p_is_acti_c49284_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='productos_p_categor_6236a2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['proveedor', 'is_active'], name='productos_p_proveed_1c52ce_idx'),
        ),
    ]
