# Generated by Django 5.2.4 on 2025-11-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_product_productos_p_slug_50559c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código SKU'),
        ),
    ]
